name: coverage-gate

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage_gate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Detecta arquivos de cobertura suportados
      - name: Detectar relatórios de cobertura
        id: cov
        run: |
          set -e
          FILES="$(git ls-files '**/jacoco*.xml' '**/coverage.xml' '**/coverage.cobertura.xml' '**/lcov.info' || true)"
          if [ -n "$FILES" ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "Nenhum relatório de cobertura encontrado; apenas registrando."
          fi

      # Gera sumário e aplica thresholds (não quebra PR por padrão)
      - name: Coverage Gate
        if: steps.cov.outputs.found == 'true'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          files: |
            **/jacoco*.xml
            **/coverage.xml
            **/coverage.cobertura.xml
            **/lcov.info
          format: markdown
          indicators: true
          output: both
          fail_below_min: false   # mude para true se quiser quebrar PR
          thresholds: '70 70 70'  # statements, branches, lines
