name: policy-check

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  conftest:
    name: Conftest (OPA)
    runs-on: ubuntu-latest
    # só roda se houver políticas rego OU diretório policy/
    if: ${{ hashFiles('policy/**/*.rego') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conftest
        uses: styra-inc/setup-conftest@v3
        with:
          version: v0.58.0
      - name: Rodar Conftest em manifests (YAML/JSON)
        run: |
          set -e
          # cole os arquivos que você deseja validar:
          TARGETS="$(git ls-files '*.yaml' '*.yml' '*.json' || true)"
          if [ -z "$TARGETS" ]; then
            echo "Sem arquivos para validar. Ok."
            exit 0
          fi
          conftest test -p policy $TARGETS -o table
