name: policy-check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  conftest:
    name: Conftest (OPA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # instala Conftest (evita action inexistente)
      - name: Install Conftest
        run: |
          set -e
          VER="0.58.0"
          curl -sSL -o conftest.tar.gz \
            "https://github.com/open-policy-agent/conftest/releases/download/v${VER}/conftest_${VER}_Linux_x86_64.tar.gz"
          sudo tar -xzf conftest.tar.gz -C /usr/local/bin conftest
          conftest --version

      # Detecta se há políticas .rego
      - name: Detectar políticas Rego
        id: detect
        run: |
          if find policy -type f -name '*.rego' 2>/dev/null | grep -q .; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      # Coleta YAML/JSON a validar
      - name: Coletar arquivos YAML/JSON
        id: collect
        if: steps.detect.outputs.found == 'true'
        run: |
          TARGETS="$(git ls-files '*.yml' '*.yaml' '*.json' | tr '\n' ' ')"
          echo "targets=$TARGETS" >> "$GITHUB_OUTPUT"

      # Executa Conftest se houver políticas e alvos
      - name: Rodar Conftest
        if: steps.detect.outputs.found == 'true' && steps.collect.outputs.targets != ''
        run: conftest test -p policy ${{ steps.collect.outputs.targets }}
