name: reusable-openapi-asyncapi
on:
  workflow_call: {}

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Lint OpenAPI (advisory)
        if: ${{ hashFiles('docs/apis-openapi/**/*.yml','docs/apis-openapi/**/*.yaml','reference-architectures/api/**/*.yml','reference-architectures/api/**/*.yaml') != '' }}
        continue-on-error: true
        shell: bash
        run: |
          npm i -g @redocly/cli
          mapfile -t files < <(git ls-files 'docs/apis-openapi/**/*.y*ml' 'reference-architectures/api/**/*.y*ml')
          for f in "${files[@]}"; do echo "OpenAPI: $f"; redocly lint "$f" || true; done

      - name: Validate AsyncAPI (advisory)
        if: ${{ hashFiles('docs/eventos-asyncapi/**/*.yml','docs/eventos-asyncapi/**/*.yaml','reference-architectures/events/**/*.yml','reference-architectures/events/**/*.yaml') != '' }}
        continue-on-error: true
        shell: bash
        run: |
          npm i -g @asyncapi/cli
          mapfile -t files < <(git ls-files 'docs/eventos-asyncapi/**/*.y*ml' 'reference-architectures/events/**/*.y*ml')
          for f in "${files[@]}"; do echo "AsyncAPI: $f"; asyncapi validate "$f" || true; done
