name: sonar

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (histórico completo para blame)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Rodrigo-Camargo-13_ARQUITETURA_ITA_PARQUE
            -Dsonar.organization=rodrigo-camargo-13
