name: sonar

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (histórico completo para blame)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Gate: só roda se os secrets existirem
      - name: Decidir execução
        id: gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          if [ -n "${SONAR_TOKEN}" ] && [ -n "${SONAR_HOST_URL}" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
            echo "Aviso: SONAR_TOKEN/SONAR_HOST_URL ausentes; job será ignorado."
          fi

      - name: Setup Java (para scanner)
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Sonar Scan
        if: steps.gate.outputs.run == 'true'
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # Com sonar-project.properties na raiz, não precisa passar args

      # (Opcional, mas recomendado) Falhar o pipeline se o Quality Gate reprovar
      - name: Quality Gate
        if: steps.gate.outputs.run == 'true'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
