name: sonar

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    # só executa se secrets existirem
    if: ${{ secrets.SONAR_TOKEN != '' && secrets.SONAR_HOST_URL != '' }}
    steps:
      - uses: actions/checkout@v4

      # (opcional) se houver Java, configurar JDK para o scanner embutido
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # Para SonarCloud, o action acima funciona igual (ele respeita sonar.organization do .properties)
