openapi: 3.0.3
info:
  title: Exemplo API de Produtos
  description: API REST de exemplo seguindo padrão institucional OpenAPI.
  version: 1.0.0
servers:
  - url: https://api.empresa.com/produtos
paths:
  /produtos:
    get:
      summary: Lista produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
components:
  schemas:
    Produto:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        preco:
          type: number
